sonata_admin:
    title: 'PHP DEV Epsilon Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    templates:
        show: 'field_types_templates/admin_product_image.html.twig'


sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
